version: '3.3'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipdevs/test}
    command: ${TEST_CMD:-npm test}
    depends_on:
      - memcached
      - fluentd

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
    
  fluentd:
    image: fluent/fluentd
    container_name: fluentd
    # volumes:
    #   - ./logs:/fluentd/log
    ports:
      - "24224:24224"
          